# Kitty theme
include ./kitty-themes/themes/Dark_Pastel.conf

font_family JetBrainsMono Nerd Font
font_size 12.0

background_opacity 0.6
window_padding_width 1 1

# Disable confirmation when close 
confirm_os_window_close 0
